_target_: autocast.nn.vit.TemporalViTBackbone
in_channels: null
out_channels: null
cond_channels: null
n_steps_output: null
n_steps_input: null
global_cond_channels: null
include_global_cond: true
mod_features: 256
hid_channels: 1024
hid_blocks: 16
temporal_method: "none"
# temporal_method: "attention"
attention_heads: 8
spatial: 2
patch_size: 1
dropout: 0.05
ffn_factor: 4