_target_: autocast.nn.vit.TemporalViTBackbone
in_channels: auto
out_channels: auto
cond_channels: auto
n_steps_output: auto
n_steps_input: auto
global_cond_channels: auto
include_global_cond: true
mod_features: 256
hid_channels: 512
hid_blocks: 16
temporal_method: "none"
attention_heads: 4
spatial: 2
patch_size: 1
dropout: 0.05
ffn_factor: 4
