_target_: autocast.encoders.dc.DCEncoder
in_channels: ${oc.select:datamodule.n_channels, null}
out_channels: 2
hid_channels: [32, 64]
hid_blocks: [2, 2]
kernel_size: 3
stride: 2
spatial: 2
pixel_shuffle: false
periodic: false
dropout: null