defaults:
  - datamodule: advection_diffusion_multichannel_64_64
  - optional simulator: null
  - optimizer: adamw
  # Or set to TheWell dataset:
  # - datamodule: the_well
  - model: autoencoder
  - trainer: default
  - logging: wandb
  # TODO: implement autoencoder eval config
  # - optional eval: default
  - _self_
  - optional experiment: null
  - optional local_experiment: null

seed: 42
experiment_name: ae

datamodule:
  autoencoder_mode: true

output:
  checkpoint_name: autoencoder.ckpt
  checkpoint_path: null  # Override checkpoint path (defaults to work_dir/checkpoint_name)
  save_config: true
  skip_test: false  # Skip running trainer.test() after training

hydra:
  searchpath:
    - file://${oc.env:PWD,.}/local_hydra
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true
