defaults:
  - /backbone@backbone: vit_small
  - _self_

_target_: autocast.processors.diffusion.DiffusionProcessor
schedule:
  _target_: azula.noise.VPSchedule
denoiser_type: karras
n_steps_output: null
n_channels_out: null
sampler_steps: 20
sampler: euler
