learning_rate: 0.001
encoder:
  _target_: auto_cast.encoders.dc.DCEncoder
  in_channels: 2
  out_channels: 16
  hid_channels: [32, 64]
  hid_blocks: [2, 2]
  kernel_size: 3
  stride: 2
  spatial: 2
  pixel_shuffle: false
  periodic: false
  dropout: null
decoder:
  _target_: auto_cast.decoders.dc.DCDecoder
  in_channels: 16
  out_channels: 2
  hid_channels: [64, 32]
  hid_blocks: [2, 2]
  kernel_size: 3
  stride: 2
  spatial: 2
  pixel_shuffle: false
  periodic: false
  dropout: null
loss:
  _target_: auto_cast.models.ae.AELoss
  losses:
    - _target_: torch.nn.MSELoss
  weights: [1.0]
