defaults:
  # - /encoder: identity
  # - /decoder: identity
  - /encoder: dc_deep
  - /decoder: dc_deep
  - /processor: flow_matching_vit
  - _self_

learning_rate: 0.0001
train_in_latent_space: true
stride: ${training.stride}
rollout_stride: ${training.rollout_stride}
teacher_forcing_ratio: 0.5
max_rollout_steps: 25
loss_func:
  _target_: torch.nn.MSELoss
