_target_: autocast.data.datamodule.SpatioTemporalDataModule
data_path: "${oc.env:AUTOCAST_DATASETS,./datasets}/reaction_diffusion"
batch_size: 16
n_steps_input: 1
n_steps_output: 4
stride: 1
verbose: false
use_normalization: false
normalization_stats:
  stats:
    mean:
      U: 0.0
      V: 0.0
    std:
      U: 1.0
      V: 1.0
    mean_delta:
      U: 0.0
      V: 0.0
    std_delta:
      U: 1.0
      V: 1.0
  core_field_names: [U, V]
  constant_field_names: []
num_workers: 0
