_target_: autocast.nn.unet.TemporalUNetBackbone
in_channels: null
out_channels: null
cond_channels: null
n_steps_output: null
n_steps_input: null
global_cond_channels: null
include_global_cond: true
mod_features: 256
hid_channels: [32, 64, 128]
hid_blocks: [2, 2, 2]
spatial: 2
periodic: false
temporal_method: "none"