defaults:
  - data: advection_diffusion_multichannel
  # Or set to TheWell dataset:
  # - data: the_well
  - model: ae
  - trainer: default
  - logging: wandb
  - _self_

seed: 42
experiment_name: ae_adm
data:
  autoencoder_mode: true
output:
  checkpoint_name: autoencoder.ckpt
  save_config: true

hydra:
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true
