defaults:
  - datamodule: advection_diffusion_multichannel
  - optional simulator: null
  - optimizer: adamw
  - model: encoder_processor_decoder
  - trainer: default
  - logging: wandb
  - _self_

seed: 42
experiment_name: epd

output:
  checkpoint_name: encoder_processor_decoder.ckpt
  save_config: true

eval:
  max_rollout_steps: 25

hydra:
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true
