defaults:
  - data: reaction_diffusion
  - encoder: permute_concat
  - decoder: channels_last
  - processor: fno
  - trainer: default
  - _self_

seed: 42
experiment_name: processor
output:
  checkpoint_name: encoder_processor_decoder.ckpt
  save_config: true

training:
  n_steps_input: 4
  n_steps_output: 4
  stride: 4
  autoencoder_checkpoint: null
  freeze_autoencoder: false

encoder_processor_decoder:
  learning_rate: 0.001
  train_processor_only: false
  loss_func:
    _target_: torch.nn.MSELoss

hydra:
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true
