defaults:
  - datamodule: miniwell
  - optional simulator: null
  - model: processor
  - trainer: default
  - logging: wandb
  - _self_

seed: 42
experiment_name: processor
output:
  checkpoint_name: processor.ckpt
  save_config: true

training:
  n_steps_input: auto
  n_steps_output: auto
  stride: auto
  rollout_stride: auto


hydra:
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true
