defaults:
  - datamodule: miniwell
  - optional simulator: null
  - optimizer: adamw
  - model: processor
  - trainer: default
  - logging: wandb
  - _self_

seed: 42
experiment_name: processor

output:
  checkpoint_name: processor.ckpt
  save_config: true


hydra:
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true
