_target_: autocast.decoders.dc.DCDecoder
in_channels: 2
out_channels: ${oc.select:datamodule.n_channels, null}
hid_channels: [256, 128, 64]
hid_blocks: [2, 2, 2]
kernel_size: 3
stride: 2
spatial: 2
pixel_shuffle: false
periodic: false
dropout: null