defaults:
  # - /encoder: identity
  # - /decoder: identity
  - /encoder: dc_deep
  - /decoder: dc_deep
  - /processor: flow_matching_vit
  - /input_noise_injector: null
  - _self_
train_in_latent_space: true
freeze_encoder_decoder: true
loss_func:
  _target_: torch.nn.MSELoss
