_target_: autocast.processors.fno.FNOProcessor
in_channels: null
out_channels: null
n_modes: [16, 16]
hidden_channels: 64
n_layers: 4
learning_rate: 0.0001
stride: ${training.stride}
teacher_forcing_ratio: 0.0
max_rollout_steps: ${training.n_steps_output}
