_target_: autocast.processors.vit.AViTProcessor
in_channels: auto 
out_channels: auto
spatial_resolution: [32, 32]
hidden_dim: 256
num_heads: 4
n_layers: 4
drop_path: 0.1
n_noise_channels: null
patch_size: 8
